const mongoose = require("mongoose");

// =====================================================
// PACK CARD SCHEMA
// =====================================================

const packCardSchema = new mongoose.Schema(
  {
    card: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Card",
      required: true,
    },

    // Probability weight used by the reveal algorithm
    pullWeight: {
      type: Number,
      required: true,
      min: 0,
      default: 1,
    },

    // Number of copies available for this pack
    quantity: {
      type: Number,
      default: 1,
      min: 0,
    },
  },
  {
    _id: false,
  }
);

// =====================================================
// PACK SCHEMA
// =====================================================

const packSchema = new mongoose.Schema(
  {
    // =================================================
    // PACK NAME
    // =================================================

    name: {
      type: String,
      required: true,
      trim: true,
    },

    // =================================================
    // SLUG
    // =================================================

    slug: {
      type: String,
      unique: true,
      index: true,
      trim: true,
    },

    // =================================================
    // DESCRIPTION
    // =================================================

    description: {
      type: String,
      default: "",
      trim: true,
    },

    // =================================================
    // PACK IMAGE
    // =================================================

    image: {
      type: String,
      default: "",
    },

    // =================================================
    // CATEGORY
    // =================================================

    category: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "PackCategory",
      required: true,
    },

    // =================================================
    // PACK SELLING PRICE
    //
    // IMPORTANT:
    // This is the price ADMIN sets for selling the pack.
    //
    // It is NOT restricted by category min/max card price.
    //
    // Example:
    //
    // Category:
    // Great = $9 - $20 card range
    //
    // Pack Price:
    // $30
    //
    // This is VALID.
    // =================================================

    packPrice: {
      type: Number,
      required: true,
      min: 0,
    },

    // =================================================
    // CARD PRICE RANGE
    //
    // This comes automatically from PackCategory.
    //
    // Example:
    //
    // Great:
    // min = 9
    // max = 20
    //
    // Cards selected randomly must be inside this range.
    // =================================================

    priceRange: {
      min: {
        type: Number,
        required: true,
        min: 0,
      },

      max: {
        type: Number,
        default: null,
        min: 0,
      },
    },

    // =================================================
    // AUTO GENERATED
    // =================================================

    autoGenerated: {
      type: Boolean,
      default: false,
    },

    // =================================================
    // CARDS PER PACK
    // =================================================

    cardsPerPack: {
      type: Number,
      required: true,
      min: 1,
      default: 5,
    },

    // =================================================
    // TOTAL STOCK
    // =================================================

    totalStock: {
      type: Number,
      default: 0,
      min: 0,
    },

    // =================================================
    // SOLD COUNT
    // =================================================

    soldCount: {
      type: Number,
      default: 0,
      min: 0,
    },

    // =================================================
    // PACK CARDS
    // =================================================

    cards: {
      type: [packCardSchema],
      default: [],
    },

    // =================================================
    // PACK STATUS
    // =================================================

    status: {
      type: String,
      enum: [
        "DRAFT",
        "PUBLISHED",
        "PAUSED",
        "ARCHIVED",
      ],
      default: "DRAFT",
    },

    // =================================================
    // CREATED BY
    // =================================================

    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
  },

  {
    timestamps: true,
  }
);

// =====================================================
// EXPORT
// =====================================================

module.exports = mongoose.model(
  "Pack",
  packSchema
);