const Pack = require("../models/Pack");
const Order = require("../models/Order");
const Wallet = require("../models/Wallet");

// =====================================================
// GET USER DASHBOARD
// GET /api/user/dashboard
// =====================================================

const getUserDashboard = async (req, res) => {
  try {
    // =====================================================
    // USER ID
    // =====================================================

    const userId =
      req.user?.id ||
      req.user?._id;

    if (!userId) {
      return res.status(401).json({
        success: false,
        message: "User not authenticated",
      });
    }

    // =====================================================
    // USER WALLET
    // =====================================================

    let wallet = await Wallet.findOne({
      user: userId,
    });

    if (!wallet) {
      wallet = await Wallet.create({
        user: userId,
        balance: 0,
      });
    }

    const walletBalance = Number(
      wallet.balance || 0
    );

    // =====================================================
    // GET PUBLISHED PACKS
    // =====================================================

    const packs = await Pack.find({
      status: "PUBLISHED",
    })
      .select(
        "name slug description image category packPrice priceRange autoGenerated cardsPerPack totalStock soldCount status createdAt updatedAt"
      )
      .populate(
        "category",
        "name slug image description minPrice maxPrice status"
      )
      .sort({
        createdAt: -1,
      })
      .lean();

    // =====================================================
    // FORMAT PACKS
    // =====================================================

    const formattedPacks = packs.map(
      (pack) => {
        const packPrice = Number(
          pack.packPrice ?? 0
        );

        return {
          ...pack,

          // Actual database price
          packPrice,

          // Also provide price for frontend compatibility
          price: packPrice,

          totalStock: Number(
            pack.totalStock ?? 0
          ),

          soldCount: Number(
            pack.soldCount ?? 0
          ),

          cardsPerPack: Number(
            pack.cardsPerPack ?? 0
          ),
        };
      }
    );

    // =====================================================
    // USER ORDERS
    // =====================================================

    const orders = await Order.find({
      user: userId,
    })
      .populate(
        "pack",
        "name packPrice price image description category"
      )
      .sort({
        createdAt: -1,
      })
      .lean();

    // =====================================================
    // FIX ORDER PACK PRICE TOO
    // =====================================================

    const formattedOrders =
      orders.map((order) => {
        if (
          order.pack &&
          typeof order.pack === "object"
        ) {
          const orderPackPrice =
            Number(
              order.pack.packPrice ??
              order.pack.price ??
              0
            );

          return {
            ...order,

            pack: {
              ...order.pack,

              packPrice:
                orderPackPrice,

              price:
                orderPackPrice,
            },
          };
        }

        return order;
      });

    // =====================================================
    // PAID ORDERS
    // =====================================================

    const paidOrders =
      formattedOrders.filter(
        (order) =>
          order.paymentStatus === "PAID"
      );

    // =====================================================
    // TOTAL PACKS
    // =====================================================

    const totalPacks =
      paidOrders.reduce(
        (total, order) =>
          total +
          Number(
            order.quantity ?? 0
          ),
        0
      );

    // =====================================================
    // TOTAL SPENT
    // =====================================================

    const totalSpent =
      paidOrders.reduce(
        (total, order) =>
          total +
          Number(
            order.amount ?? 0
          ),
        0
      );

    // =====================================================
    // DEBUG
    // =====================================================

    console.log(
      "USER DASHBOARD PACKS:"
    );

    console.log(
      formattedPacks.map(
        (pack) => ({
          id: pack._id,
          name: pack.name,
          packPrice:
            pack.packPrice,
          price:
            pack.price,
        })
      )
    );

    // =====================================================
    // RESPONSE
    // =====================================================

    return res.status(200).json({
      success: true,

      data: {
        // PACKS
        packs: formattedPacks,

        // ORDERS
        orders: formattedOrders,

        // WALLET
        walletBalance,

        // STATS
        stats: {
          totalPacks,

          totalOrders:
            formattedOrders.length,

          totalSpent,

          totalOpenings: 0,

          collectionCount: 0,

          walletBalance,
        },
      },
    });

  } catch (error) {
    console.error(
      "User dashboard error:",
      error
    );

    return res.status(500).json({
      success: false,
      message: "Server error",
    });
  }
};

// =====================================================
// EXPORT
// =====================================================

module.exports = {
  getUserDashboard,
};